from __future__ import annotations

import json
import re
import sqlite3
import uuid
from contextlib import contextmanager
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterator

from pydantic import BaseModel

# An itinerary is kept for this long after its *last change* (creation, or the most recent
# search run added to it); after that it's hidden from every query and purged on the next
# session start. Read-time filtering is what guarantees the window -- the purge only reclaims
# space, so correctness never depends on when (or whether) a purge last ran.
ITINERARY_RETENTION = timedelta(hours=72)

MAX_ITINERARY_NAME_LENGTH = 80

# Characters an itinerary name may contain: letters/digits in any script, spaces, and common
# punctuation. Names are rendered as Markdown by Streamlit (button labels support links and
# images; headings go through st.markdown), and a session's URL can be shared, so a name must
# not be able to carry a link, an image, or HTML -- no brackets, backticks, angle brackets,
# '#', '*', '!' or '|'. Validating once at creation covers every place a name is displayed.
_ITINERARY_NAME_PATTERN = re.compile(r"[\w \-.,'&()/:?+]+")

_SCHEMA = """
CREATE TABLE IF NOT EXISTS sessions (
    session_id   TEXT PRIMARY KEY,
    created_at   TEXT NOT NULL,
    last_seen_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS search_runs (
    run_id            TEXT PRIMARY KEY,
    session_id        TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    created_at        TEXT NOT NULL,
    destination       TEXT NOT NULL,
    travel_start_date TEXT,
    result_json       TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_search_runs_session ON search_runs(session_id, created_at);

CREATE TABLE IF NOT EXISTS itineraries (
    itinerary_id TEXT PRIMARY KEY,
    session_id   TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    name         TEXT NOT NULL COLLATE NOCASE,
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    UNIQUE (session_id, name)
);
CREATE INDEX IF NOT EXISTS idx_itineraries_session ON itineraries(session_id, updated_at);

CREATE TABLE IF NOT EXISTS itinerary_items (
    itinerary_id TEXT NOT NULL REFERENCES itineraries(itinerary_id) ON DELETE CASCADE,
    run_id       TEXT NOT NULL REFERENCES search_runs(run_id) ON DELETE CASCADE,
    added_at     TEXT NOT NULL,
    PRIMARY KEY (itinerary_id, run_id)
);
"""


class DuplicateItineraryNameError(ValueError):
    pass


class ItineraryNotFoundError(LookupError):
    pass


class SearchRunNotFoundError(LookupError):
    pass


# One completed itinerary-generation run that was saved to an itinerary, stored whole (the dict build_itineraries returns)
# so it can be re-rendered exactly as it was shown. Prices inside it are a snapshot as of
# `created_at`, not live quotes.
class SearchRun(BaseModel):
    run_id: str
    created_at: datetime
    destination: str
    travel_start_date: date | None = None
    result: dict[str, Any]

    @property
    def label(self) -> str:
        when = f" ({self.travel_start_date.isoformat()})" if self.travel_start_date else ""
        return f"{self.destination}{when}"


# A user-named collection of saved search runs. `itinerary_id` is generated by the app and
# never shown to or edited by the user; `name` is unique per session (case-insensitive).
class Itinerary(BaseModel):
    itinerary_id: str
    name: str
    created_at: datetime
    updated_at: datetime
    run_count: int = 0

    @property
    def expires_at(self) -> datetime:
        return self.updated_at + ITINERARY_RETENTION


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# Timestamps are stored as fixed-format UTC ISO-8601 strings so that SQL string comparison
# orders them correctly.
def _ts(value: datetime) -> str:
    return value.astimezone(timezone.utc).isoformat(timespec="seconds")


def is_valid_session_id(value: str | None) -> bool:
    if not value:
        return False
    try:
        return str(uuid.UUID(value, version=4)) == value
    except ValueError:
        return False


def new_session_id() -> str:
    return str(uuid.uuid4())


# SQLite-backed store for per-session search runs and itineraries. Every public method is
# scoped by `session_id`, so one session can never read or modify another session's rows
# even when handed a valid itinerary/run id.
#
# Opens a short-lived connection per call rather than sharing one: Streamlit runs each
# browser session's script on its own thread and reruns it on every interaction, and a
# per-call connection sidesteps sqlite3's same-thread restriction without any locking.
class SessionStore:
    def __init__(self, db_path: str | Path):
        self._db_path = str(db_path)
        if self._db_path != ":memory:":
            Path(self._db_path).parent.mkdir(parents=True, exist_ok=True)
        with self._connect() as conn:
            conn.execute("PRAGMA journal_mode=WAL")
            conn.executescript(_SCHEMA)

    @contextmanager
    def _connect(self) -> Iterator[sqlite3.Connection]:
        conn = sqlite3.connect(self._db_path, timeout=10)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys=ON")
        try:
            with conn:
                yield conn
        finally:
            conn.close()

    def touch_session(self, session_id: str, now: datetime | None = None) -> None:
        with self._connect() as conn:
            self._touch(conn, session_id, _ts(now or _utcnow()))

    # Upserts the session row. Every write calls this in its own transaction, so a long-idle
    # tab whose empty session row was purged by another session's start-up can still save.
    @staticmethod
    def _touch(conn: sqlite3.Connection, session_id: str, stamp: str) -> None:
        conn.execute(
            "INSERT INTO sessions (session_id, created_at, last_seen_at) VALUES (?, ?, ?) "
            "ON CONFLICT(session_id) DO UPDATE SET last_seen_at = excluded.last_seen_at",
            (session_id, stamp, stamp),
        )

    # Deletes expired itineraries (their item links cascade), then every run no longer in
    # any itinerary -- searches are only ever stored as part of an itinerary, so a run left
    # without one is orphaned -- then sessions left with nothing in them that haven't been
    # seen within the itinerary window. Returns the number of itineraries removed.
    def purge_expired(self, now: datetime | None = None) -> int:
        now = now or _utcnow()
        itinerary_cutoff = _ts(now - ITINERARY_RETENTION)
        with self._connect() as conn:
            removed = conn.execute(
                "DELETE FROM itineraries WHERE updated_at < ?", (itinerary_cutoff,)
            ).rowcount
            conn.execute(
                "DELETE FROM search_runs WHERE run_id NOT IN (SELECT run_id FROM itinerary_items)"
            )
            conn.execute(
                "DELETE FROM sessions WHERE last_seen_at < ? "
                "AND session_id NOT IN (SELECT session_id FROM itineraries) "
                "AND session_id NOT IN (SELECT session_id FROM search_runs)",
                (itinerary_cutoff,),
            )
        return removed

    # Stores a search run and adds it to an itinerary in one transaction, so a search is never
    # stored without belonging to an itinerary. Bumps the itinerary's `updated_at`, which
    # restarts its retention window. Returns the new run's id, which add_run_to_itinerary
    # accepts for filing the same search into further itineraries.
    def save_search_to_itinerary(
        self,
        session_id: str,
        itinerary_id: str,
        result: dict[str, Any],
        travel_start_date: date | None,
        now: datetime | None = None,
    ) -> str:
        now = now or _utcnow()
        run_id = str(uuid.uuid4())
        stamp = _ts(now)
        with self._connect() as conn:
            if not self._itinerary_is_live(conn, session_id, itinerary_id, now):
                raise ItineraryNotFoundError(itinerary_id)
            self._touch(conn, session_id, stamp)
            conn.execute(
                "INSERT INTO search_runs "
                "(run_id, session_id, created_at, destination, travel_start_date, result_json) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (
                    run_id,
                    session_id,
                    stamp,
                    str(result.get("destination", "Unknown destination")),
                    travel_start_date.isoformat() if travel_start_date else None,
                    json.dumps(result),
                ),
            )
            conn.execute(
                "INSERT INTO itinerary_items (itinerary_id, run_id, added_at) VALUES (?, ?, ?)",
                (itinerary_id, run_id, stamp),
            )
            conn.execute(
                "UPDATE itineraries SET updated_at = ? WHERE itinerary_id = ?", (stamp, itinerary_id)
            )
        return run_id

    def create_itinerary(self, session_id: str, name: str, now: datetime | None = None) -> str:
        clean_name = " ".join(name.split())
        if not clean_name:
            raise ValueError("Itinerary name can't be blank.")
        if len(clean_name) > MAX_ITINERARY_NAME_LENGTH:
            raise ValueError(f"Itinerary name must be {MAX_ITINERARY_NAME_LENGTH} characters or fewer.")
        if not _ITINERARY_NAME_PATTERN.fullmatch(clean_name):
            raise ValueError(
                "Itinerary name can only contain letters, numbers, spaces and - . , ' & ( ) / : ? +"
            )

        itinerary_id = str(uuid.uuid4())
        stamp = _ts(now or _utcnow())
        with self._connect() as conn:
            self._touch(conn, session_id, stamp)
            try:
                conn.execute(
                    "INSERT INTO itineraries (itinerary_id, session_id, name, created_at, updated_at) "
                    "VALUES (?, ?, ?, ?, ?)",
                    (itinerary_id, session_id, clean_name, stamp, stamp),
                )
            except sqlite3.IntegrityError as exc:
                raise DuplicateItineraryNameError(
                    f'An itinerary named "{clean_name}" already exists.'
                ) from exc
        return itinerary_id

    # Adds an already-saved run to another itinerary (a no-op if it's already there) and bumps the itinerary's
    # `updated_at`, which restarts its retention window.
    def add_run_to_itinerary(
        self, session_id: str, itinerary_id: str, run_id: str, now: datetime | None = None
    ) -> None:
        now = now or _utcnow()
        stamp = _ts(now)
        with self._connect() as conn:
            if not self._itinerary_is_live(conn, session_id, itinerary_id, now):
                raise ItineraryNotFoundError(itinerary_id)
            self._touch(conn, session_id, stamp)
            run_owned = conn.execute(
                "SELECT 1 FROM search_runs WHERE run_id = ? AND session_id = ?",
                (run_id, session_id),
            ).fetchone()
            if run_owned is None:
                raise SearchRunNotFoundError(run_id)
            conn.execute(
                "INSERT OR IGNORE INTO itinerary_items (itinerary_id, run_id, added_at) VALUES (?, ?, ?)",
                (itinerary_id, run_id, stamp),
            )
            conn.execute(
                "UPDATE itineraries SET updated_at = ? WHERE itinerary_id = ?", (stamp, itinerary_id)
            )

    def list_recent_itineraries(self, session_id: str, now: datetime | None = None) -> list[Itinerary]:
        cutoff = _ts((now or _utcnow()) - ITINERARY_RETENTION)
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT i.itinerary_id, i.name, i.created_at, i.updated_at, "
                "COUNT(ii.run_id) AS run_count "
                "FROM itineraries i LEFT JOIN itinerary_items ii ON ii.itinerary_id = i.itinerary_id "
                "WHERE i.session_id = ? AND i.updated_at >= ? "
                "GROUP BY i.itinerary_id ORDER BY i.updated_at DESC",
                (session_id, cutoff),
            ).fetchall()
        return [Itinerary(**dict(row)) for row in rows]

    def get_itinerary(
        self, session_id: str, itinerary_id: str, now: datetime | None = None
    ) -> Itinerary | None:
        return next(
            (i for i in self.list_recent_itineraries(session_id, now) if i.itinerary_id == itinerary_id),
            None,
        )

    def list_itinerary_runs(
        self, session_id: str, itinerary_id: str, now: datetime | None = None
    ) -> list[SearchRun]:
        now = now or _utcnow()
        with self._connect() as conn:
            if not self._itinerary_is_live(conn, session_id, itinerary_id, now):
                return []
            rows = conn.execute(
                "SELECT r.* FROM search_runs r "
                "JOIN itinerary_items ii ON ii.run_id = r.run_id "
                "WHERE ii.itinerary_id = ? ORDER BY ii.added_at DESC",
                (itinerary_id,),
            ).fetchall()
        return [self._row_to_run(row) for row in rows]

    @staticmethod
    def _itinerary_is_live(
        conn: sqlite3.Connection, session_id: str, itinerary_id: str, now: datetime
    ) -> bool:
        row = conn.execute(
            "SELECT 1 FROM itineraries WHERE itinerary_id = ? AND session_id = ? AND updated_at >= ?",
            (itinerary_id, session_id, _ts(now - ITINERARY_RETENTION)),
        ).fetchone()
        return row is not None

    @staticmethod
    def _row_to_run(row: sqlite3.Row) -> SearchRun:
        return SearchRun(
            run_id=row["run_id"],
            created_at=row["created_at"],
            destination=row["destination"],
            travel_start_date=row["travel_start_date"],
            result=json.loads(row["result_json"]),
        )
